version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "8081:5000"
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "technical_test:create_app()"]
    environment:
      - APP_SETTINGS=instance/settings.json
    volumes:
      - ./instance:/var/app/instance
      - ./technical_test:/var/app/technical_test
    restart: on-failure
    depends_on:
      - mongo


  mongo:
    image: mongo
    ports:
      - "27017:27017"
